### ISSUE TITLE
Ничего не происходит после запуска?

### ISSUE THREAD

**Issue by baimurzin** [HeadLightSecurity/vkmitm#4]
Такой вопрос: все что нужно сделать для сниффа - это запустить соответствующей командой из реадме? Или же нужно сначало arp спуфинг сделать с роутером. 
Просто после запуска ничего не происходит - пусто. Пробовал отсылать как с http, так и с https сообщения, но в консоли не отобразились.
Нужна подсказка вообщем.

**Comment by ishr00m** [comment]
@baimurzin i did try to run as well, also no result.
I got just only warning about iPv6, that's all.

**Comment by Enyaarrio** [comment]
Скачал архив, распаковал на рабочем столе и при запуске ./sniff_vk.py -i wlan0 в консоли отображаются 2-3 сообщения и больше ничего не происходит. Помогает только перезапуск. Что делать?

**Comment by jidckii** [comment]
Скорее всего для начала надо перевести сереврй интерфейс в неразборчивый режим, что бы он все пакеты захватывал! Ну и кое-что же вифи длржна быть открытой ! Хотя я сегодня пробовал, тоже успехом особо не увенчалось ...

**Comment by HeadLightSecurity** [comment]
Для начала нужно произвести arp-спуфинг устройства жертвы, после этого весь трафик пойдет через нас, далее запускаем скрипт на нужном сетевом интерфейсе. Подробнее в видео - https://www.youtube.com/watch?v=VS6vyTgRlRo
