### ISSUE TITLE
Exception RuntimeError

### ISSUE THREAD

**Issue by dmpanch** [HeadLightSecurity/vkmitm#5]
After installing libdnet, scapy and pcapy on El Captain I tried to sniff. Except error about IPv6 I got this one:

Exception RuntimeError: 'pcapObject must be initialized via open_live(), open_offline(), or open_dead() methods' in <bound method _PcapWrapper_libpcap.__del__ of <pcap.pcapObject; proxy of <Swig Object of type 'pcapObject *' at 0x7fa7cc8f6980> >> ignored

Any ideas?

**Comment by jidckii** [comment]
using SUDO

С Уважением, Медведев Евгений.

2015-10-19 15:53 GMT+05:00 Dmitriy notifications@github.com:

**Comment by dmpanch** [comment]
Nothing changed.

![screenshot 2015-10-19 13 58 58](https://cloud.githubusercontent.com/assets/4539449/10576109/9390dc24-7669-11e5-9130-78c3ffce82d9.png)

**Comment by jidckii** [comment]
what OS ?

С Уважением, Медведев Евгений.

2015-10-19 15:58 GMT+05:00 Dmitriy notifications@github.com:

**Comment by jidckii** [comment]
I do not speak English, you know Russian?

С Уважением, Медведев Евгений.

2015-10-19 15:58 GMT+05:00 Dmitriy notifications@github.com:

**Comment by dmpanch** [comment]
OS X 10.11.1

понедельник, 19 октября 2015 г. пользователь jidckii написал:

> what OS ?
> 
> С Уважением, Медведев Евгений.
> 
> 2015-10-19 15:58 GMT+05:00 Dmitriy <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
> 
> > Nothing changed.
> > 
> > Exception RuntimeError: 'pcapObject must be initialized via open_live(),
> > open_offline(), or open_dead() methods' in >> ignored
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/HeadLightSecurity/vkmitm/issues/5#issuecomment-149184694
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HeadLightSecurity/vkmitm/issues/5#issuecomment-149185176
> .

## 

Best regards,
Dmitriy Panchenko

**Comment by dmpanch** [comment]
Конечно я знаю русский)

понедельник, 19 октября 2015 г. пользователь jidckii написал:

> I do not speak English, you know Russian?
> 
> С Уважением, Медведев Евгений.
> 
> 2015-10-19 15:58 GMT+05:00 Dmitriy <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
> 
> > Nothing changed.
> > 
> > Exception RuntimeError: 'pcapObject must be initialized via open_live(),
> > open_offline(), or open_dead() methods' in >> ignored
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/HeadLightSecurity/vkmitm/issues/5#issuecomment-149184694
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HeadLightSecurity/vkmitm/issues/5#issuecomment-149185310
> .

## 

Best regards,
Dmitriy Panchenko

**Comment by jidckii** [comment]
Извини, в вопросе ОС Х не помогу. Я использую Ubuntu!
Я делал так sudo ifconfig wlan0 promisc  что бы перевести интерфейс в
неразборчивый режим и захватывать все пакеты в открытой вифи сети.
Как это сделать на ОС Х  я не подскажу, смотри ifconfig --help
Но у меня тоже не получилось поэксплуатировать дыру, так что не факт, что
сработает.

С Уважением, Медведев Евгений.

2015-10-19 16:11 GMT+05:00 Dmitriy notifications@github.com:

**Comment by dmpanch** [comment]
Проблема была в неверном имени интерфейса. Для OS X promisc mode включается ключом -I.

И дыра не нова, лет 5 назад юзал droidsheep, уверен, что до сих пор работает, т.к. https юзают далеко не все.
